---
- name: Ensure group "nginx" exists
  group:
    name: nginx
    state: present

- name: Add the user nginx
  user:
    name: nginx
    shell: /bin/nologin
    groups: nginx

# - name: Check if nginx package is installed
#   shell: dpkg-query -l 'nginx'
#   register: nginx_result

- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes
#  when: nginx_result.stdout != ""

- name: Add NGINX configuration from template
  template:
    src: files/default.conf.j2
    dest: /etc/nginx/sites-enabled/default
    owner: nginx
    group: nginx
    mode: 0644
  notify: restart nginx